import "./globals.css";

import type { Metadata } from "next";

import { ClerkProvider } from "@clerk/nextjs";
import { deDE } from "@clerk/localizations";

import { Chivo, Inter } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import TanStackProvider from "@/components/providers/TanStackProvider";
import NavbarMobile from "@/components/NavbarMobile";

const inter = Inter({ subsets: ["latin"] });
const chivo = Chivo({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider localization={deDE}>
      <html lang="en">
        <body suppressHydrationWarning className={chivo.className}>
          <TanStackProvider>
            {/* <Navbar />
            <NavbarMobile /> */}
            {children}
            <Footer />
            <Toaster richColors theme="light" />
          </TanStackProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
